export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_PRODUCTS_EXCLUSIVES = "GET_PRODUCTS_EXCLUSIVES";
export const GET_EXCLUSIVES_SUCCESS = "GET_EXCLUSIVES_SUCCESS";
export const GET_EXCLUSIVES_FAIL = "GET_EXCLUSIVES_FAIL";

export const GET_PRODUCTS_PROMOTION = "GET_PRODUCTS_PROMOTION";
export const GET_PROMOTION_SUCCESS = "GET_PROMOTION_SUCCESS";
export const GET_PROMOTION_FAIL = "GET_PROMOTION_FAIL";

export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const SEARCH_PRODUCT_SUCCESS = "SEARCH_PRODUCT_SUCCESS";
export const SEARCH_PRODUCT_FAIL = "SEARCH_PRODUCT_FAIL";

export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAIL = "GET_PRODUCT_DETAILS_FAIL";

export const GET_PRODUCTS_FAVORITE = "GET_PRODUCT_FAVORITE";
export const GET_PRODUCTS_FAVORITE_SUCCESS = "GET_PRODUCT_FAVORITE_SUCCESS";
export const GET_PRODUCTS_FAVORITE_FAIL = "GET_PRODUCT_FAVORITE_FAIL";